services:
  backend:
    image: link-shortner
    container_name: link-shortner
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    

  db:
    image: postgres:17
    container_name: link-shortner-pg
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:8
    container_name: link-shortner-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: